# Change these first
owner: rodenacker # Your GitHub username
repo: easy-upptime # Your GitHub repository name

# Add your sites here
sites:
   - name: Form2Channel
     url: https://showcase.api.linx.twenty57.net/Form2Channel/health?Input=yes
     assignees: 
       - rodenacker
   - name: Unixtime
     url: https://showcase.api.linx.twenty57.net/UnixTime/fromunix?timestamp=1549892280
     assignees: 
       - rodenacker
   - name: F2CTest
     url: https://housefrau.me/test/test_complete_re3.html
     assignees: 
       - rodenacker
   - name: BrokenSite
     url: https://brokensite.broken
     assignees: 
       - rodenacker

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /easy-upptime
  logoUrl: https://rodenacker.github.io/easy-upptime/assets/upptime-icon.svg
  name: Easy-Upptime
  theme: light
  introTitle: "**Easy Upptime**"
  introMessage: This is an example of how we can use GitHub to check if our Linx API's are up
  navbar:
    - title: Status
      href: /easy-upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
